name: Sync External Assets

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  update-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: Clear release branch
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

      - name: Download mihomo smart core
        run: |
          API="https://api.github.com/repos/vernesong/mihomo/releases"
          ASSET_REGEX="^mihomo-linux-arm64-alpha-smart-.*\\.gz$"

          alpha_url=$(
            curl -sfL \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              "$API" \
            | jq -r --arg regex "$ASSET_REGEX" '
                .[]
                | select(.prerelease == true)
                | .assets[]
                | select(.name | test($regex))
                | .browser_download_url
              ' \
            | head -n 1
          )

          if [[ -z "$alpha_url" ]]; then
            echo "❌ 未找到 mihomo-linux-arm64-alpha-smart" >&2
            exit 1
          fi

          echo "下载链接：$alpha_url"
          curl -sfL -o mihomo-smart.gz "$alpha_url"

      - name: Download mihomo latest core
        run: |
          API="https://api.github.com/repos/MetaCubeX/mihomo/releases/latest"
          ASSET_REGEX="^mihomo-linux-arm64-.*\\.gz$"

          latest_url=$(
            curl -sfL \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              "$API" \
            | jq -r --arg regex "$ASSET_REGEX" '
                .assets[]
                | select(.name | test($regex))
                | .browser_download_url
              ' \
            | head -n 1
          )

          if [[ -z "$latest_url" ]]; then
            echo "❌ 未找到 mihomo-linux-arm64" >&2
            exit 1
          fi

          echo "下载链接：$latest_url"
          curl -sfL -o mihomo-latest.gz $latest_url

      - name: Download Zashboard
        run: |
          curl -sfL -o dist-misans-only.zip https://github.com/Zephyruso/zashboard/releases/latest/download/dist-misans-only.zip

      - name: Download mihomo model
        run: |
          curl -sfL -o Model.bin https://github.com/vernesong/mihomo/releases/download/LightGBM-Model/Model-large.bin

      - name: Commit & Push to release branch
        run: |
          BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')

          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "Update on $BUILDTIME"
          git push origin release
